default_agent: agent007
agents:
  agent007:
    name: agent007
    language: python
    node_version: '20'
    entrypoint: /Users/vishalpandey/Developer/litecone/agents/agent007/agent007/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/vishalpandey/Developer/litecone/agents/agent007
    aws:
      execution_role: arn:aws:iam::813923511679:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-084228a16d
      execution_role_auto_create: false
      account: '813923511679'
      region: us-east-1
      ecr_repository: 813923511679.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent007
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent007-Ew26m0BY4C
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:813923511679:runtime/agent007-Ew26m0BY4C
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agent007-builder
      execution_role: arn:aws:iam::813923511679:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-084228a16d
      source_bucket: bedrock-agentcore-codebuild-sources-813923511679-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
